package exporter

import (
	"fmt"
	"html"
	"strings"

	"github.com/neko233-com/bytemsg233/pkg/codegen"
	"github.com/neko233-com/bytemsg233/pkg/schema"
)

func Markdown(s *schema.Schema) []byte {
	var buf strings.Builder

	buf.WriteString("# ByteMsg Protocol\n\n")
	buf.WriteString(fmt.Sprintf("- Schema: `%s`\n", s.Version))
	buf.WriteString(fmt.Sprintf("- Package: `%s`\n\n", s.Package))

	if len(s.Enums) > 0 {
		buf.WriteString("## Enums\n\n")
		for _, enumName := range codegen.SortedEnumNames(s) {
			enum := s.Enums[enumName]
			buf.WriteString(fmt.Sprintf("### %s\n\n", enumName))
			if enum.Description != nil {
				buf.WriteString(descriptionLine(enum.Description))
				buf.WriteString("\n")
			}
			buf.WriteString("| Name | Value |\n|---|---:|\n")
			for _, value := range codegen.SortedEnumValues(enum) {
				buf.WriteString(fmt.Sprintf("| `%s` | %d |\n", value.Name, value.Value))
			}
			buf.WriteString("\n")
		}
	}

	if len(s.Messages) > 0 {
		buf.WriteString("## Messages\n\n")
		for _, msgName := range codegen.SortedMessageNames(s) {
			msg := s.Messages[msgName]
			buf.WriteString(fmt.Sprintf("### %s\n\n", msgName))
			if msg.PacketID > 0 {
				buf.WriteString(fmt.Sprintf("- Packet ID: `%d`\n\n", msg.PacketID))
			}
			if msg.Description != nil {
				buf.WriteString(descriptionLine(msg.Description))
				buf.WriteString("\n")
			}
			buf.WriteString("| Tag | Field | Kind | Type | Description |\n|---:|---|---|---|---|\n")
			for _, fieldName := range codegen.SortedFieldNames(msg) {
				field := msg.Fields[fieldName]
				desc := ""
				if field.Description != nil {
					desc = inlineDescription(field.Description)
				}
				buf.WriteString(fmt.Sprintf("| %d | `%s` | %s | `%s` | %s |\n", field.Tag, fieldName, fieldKind(s, field.Type), field.Type, desc))
			}
			buf.WriteString("\n")
		}
	}

	buf.WriteString("## CLI\n\n")
	buf.WriteString("```bash\n")
	buf.WriteString("bytemsg233 compile protocol.bmsg.json -l go,csharp,typescript,rust,java -o ./gen\n")
	buf.WriteString("bytemsg233 install-lib csharp --to ./Assets/Plugins/ByteMsg233\n")
	buf.WriteString("```\n")

	return []byte(buf.String())
}

func HTML(s *schema.Schema) []byte {
	md := string(Markdown(s))
	title := "ByteMsg Protocol"
	if s.Package != "" {
		title = s.Package + " Protocol"
	}

	var buf strings.Builder
	buf.WriteString("<!DOCTYPE html>\n<html lang=\"zh-CN\">\n<head>\n")
	buf.WriteString("<meta charset=\"UTF-8\">\n")
	buf.WriteString("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n")
	buf.WriteString(fmt.Sprintf("<title>%s</title>\n", html.EscapeString(title)))
	buf.WriteString("<style>")
	buf.WriteString("body{margin:0;font-family:ui-sans-serif,system-ui,-apple-system,BlinkMacSystemFont,'Segoe UI',sans-serif;background:#101820;color:#edf3ee;line-height:1.65}")
	buf.WriteString("main{max-width:1120px;margin:0 auto;padding:48px 24px 80px}")
	buf.WriteString("h1{font-size:clamp(2.4rem,6vw,5rem);line-height:.95;letter-spacing:-.06em;margin:0 0 24px}")
	buf.WriteString("h2{margin-top:48px;border-top:1px solid rgba(255,255,255,.14);padding-top:28px}")
	buf.WriteString("h3{margin-top:32px;color:#f0c776}")
	buf.WriteString("table{width:100%;border-collapse:collapse;margin:16px 0 28px;background:rgba(255,255,255,.04);border-radius:18px;overflow:hidden}")
	buf.WriteString("th,td{padding:13px 14px;border-bottom:1px solid rgba(255,255,255,.1);text-align:left;vertical-align:top}")
	buf.WriteString("th{color:#9fb0a7;font-weight:600}")
	buf.WriteString("code,pre{font-family:ui-monospace,SFMono-Regular,Consolas,monospace}")
	buf.WriteString("code{color:#8fe0c9}")
	buf.WriteString("pre{padding:18px;border-radius:18px;background:#090f14;overflow:auto}")
	buf.WriteString(".meta{display:flex;gap:12px;flex-wrap:wrap;margin:0 0 28px;color:#9fb0a7}")
	buf.WriteString(".pill{border:1px solid rgba(255,255,255,.14);border-radius:999px;padding:8px 12px;background:rgba(255,255,255,.04)}")
	buf.WriteString("</style>\n</head>\n<body>\n<main>\n")
	buf.WriteString(fmt.Sprintf("<h1>%s</h1>\n", html.EscapeString(title)))
	buf.WriteString("<div class=\"meta\">")
	buf.WriteString(fmt.Sprintf("<span class=\"pill\">schema %s</span>", html.EscapeString(s.Version)))
	buf.WriteString(fmt.Sprintf("<span class=\"pill\">package %s</span>", html.EscapeString(s.Package)))
	buf.WriteString("<span class=\"pill\">generated by bytemsg233</span></div>\n")
	buf.WriteString(markdownToSimpleHTML(md))
	buf.WriteString("\n</main>\n</body>\n</html>\n")
	return []byte(buf.String())
}

func Bmsg(s *schema.Schema) []byte {
	var buf strings.Builder

	buf.WriteString(fmt.Sprintf("schema: %s\n", s.Version))
	buf.WriteString(fmt.Sprintf("package: %s\n\n", s.Package))

	for _, enumName := range codegen.SortedEnumNames(s) {
		enum := s.Enums[enumName]
		buf.WriteString(fmt.Sprintf("enum %s {\n", enumName))
		for _, value := range codegen.SortedEnumValues(enum) {
			buf.WriteString(fmt.Sprintf("    %s = %d\n", value.Name, value.Value))
		}
		buf.WriteString("}\n\n")
	}

	for _, msgName := range codegen.SortedMessageNames(s) {
		msg := s.Messages[msgName]
		if msg.PacketID > 0 {
			buf.WriteString(fmt.Sprintf("// packetId: %d\n", msg.PacketID))
		}
		buf.WriteString(fmt.Sprintf("message %s {\n", msgName))
		for _, fieldName := range codegen.SortedFieldNames(msg) {
			field := msg.Fields[fieldName]
			buf.WriteString(fmt.Sprintf("    %s %s = %d", field.Type, fieldName, field.Tag))
			if field.Description != nil {
				buf.WriteString(fmt.Sprintf(" // %q | %q", field.Description.Zh, field.Description.En))
			}
			buf.WriteString("\n")
		}
		buf.WriteString("}\n\n")
	}

	return []byte(buf.String())
}

func markdownToSimpleHTML(markdown string) string {
	var buf strings.Builder
	inTable := false
	inCode := false
	for _, line := range strings.Split(markdown, "\n") {
		trimmed := strings.TrimSpace(line)
		if strings.HasPrefix(trimmed, "```") {
			if inCode {
				buf.WriteString("</code></pre>\n")
				inCode = false
			} else {
				buf.WriteString("<pre><code>")
				inCode = true
			}
			continue
		}
		if inCode {
			buf.WriteString(html.EscapeString(line))
			buf.WriteString("\n")
			continue
		}
		if strings.HasPrefix(trimmed, "|") && strings.HasSuffix(trimmed, "|") {
			if strings.Contains(trimmed, "---") {
				continue
			}
			cells := splitMarkdownTableRow(trimmed)
			if !inTable {
				buf.WriteString("<table>\n")
				inTable = true
			}
			buf.WriteString("<tr>")
			for _, cell := range cells {
				buf.WriteString("<td>")
				buf.WriteString(inlineMarkdown(cell))
				buf.WriteString("</td>")
			}
			buf.WriteString("</tr>\n")
			continue
		}
		if inTable {
			buf.WriteString("</table>\n")
			inTable = false
		}
		switch {
		case strings.HasPrefix(trimmed, "# "):
			buf.WriteString(fmt.Sprintf("<h1>%s</h1>\n", inlineMarkdown(strings.TrimSpace(strings.TrimPrefix(trimmed, "# ")))))
		case strings.HasPrefix(trimmed, "## "):
			buf.WriteString(fmt.Sprintf("<h2>%s</h2>\n", inlineMarkdown(strings.TrimSpace(strings.TrimPrefix(trimmed, "## ")))))
		case strings.HasPrefix(trimmed, "### "):
			buf.WriteString(fmt.Sprintf("<h3>%s</h3>\n", inlineMarkdown(strings.TrimSpace(strings.TrimPrefix(trimmed, "### ")))))
		case strings.HasPrefix(trimmed, "- "):
			buf.WriteString(fmt.Sprintf("<p>%s</p>\n", inlineMarkdown(strings.TrimSpace(strings.TrimPrefix(trimmed, "- ")))))
		case trimmed == "":
			continue
		default:
			buf.WriteString(fmt.Sprintf("<p>%s</p>\n", inlineMarkdown(trimmed)))
		}
	}
	if inTable {
		buf.WriteString("</table>\n")
	}
	if inCode {
		buf.WriteString("</code></pre>\n")
	}
	return buf.String()
}

func splitMarkdownTableRow(row string) []string {
	row = strings.Trim(row, "|")
	parts := strings.Split(row, "|")
	for i := range parts {
		parts[i] = strings.TrimSpace(parts[i])
	}
	return parts
}

func inlineMarkdown(value string) string {
	escaped := html.EscapeString(value)
	parts := strings.Split(escaped, "`")
	for i := 1; i < len(parts); i += 2 {
		parts[i] = "<code>" + parts[i] + "</code>"
	}
	return strings.Join(parts, "")
}

func descriptionLine(desc *schema.Description) string {
	return fmt.Sprintf("> zh: %s\n>\n> en: %s\n", desc.Zh, desc.En)
}

func inlineDescription(desc *schema.Description) string {
	if desc.Zh != "" && desc.En != "" {
		return fmt.Sprintf("%s / %s", desc.Zh, desc.En)
	}
	if desc.Zh != "" {
		return desc.Zh
	}
	return desc.En
}

func fieldKind(s *schema.Schema, fieldType string) string {
	switch {
	case strings.HasPrefix(fieldType, "list<"):
		return "list"
	case strings.HasPrefix(fieldType, "map<"):
		return "map"
	}
	if s != nil {
		if _, ok := s.Enums[fieldType]; ok {
			return "enum"
		}
		if _, ok := s.Messages[fieldType]; ok {
			return "message"
		}
	}
	return "scalar"
}
