package binary

import (
	"encoding/base64"
	"encoding/json"
	"fmt"
	"reflect"
	"sort"
	"strings"
)

// MarshalPrettyString formats generated ByteMsg233 structs as indented JSON for debug output.
func MarshalPrettyString(value any) (string, error) {
	pretty, err := toPrettyValue(reflect.ValueOf(value))
	if err != nil {
		return "", err
	}
	data, err := json.MarshalIndent(pretty, "", "  ")
	if err != nil {
		return "", err
	}
	return string(data), nil
}

func toPrettyValue(value reflect.Value) (any, error) {
	if !value.IsValid() {
		return nil, nil
	}
	if value.Kind() == reflect.Interface {
		if value.IsNil() {
			return nil, nil
		}
		return toPrettyValue(value.Elem())
	}
	if value.Kind() == reflect.Pointer {
		if value.IsNil() {
			return nil, nil
		}
		return toPrettyValue(value.Elem())
	}

	switch value.Kind() {
	case reflect.Struct:
		result := make(map[string]any, value.NumField())
		valueType := value.Type()
		for i := 0; i < value.NumField(); i++ {
			fieldInfo := valueType.Field(i)
			if fieldInfo.PkgPath != "" {
				continue
			}
			fieldName := prettyFieldName(fieldInfo)
			if fieldName == "-" {
				continue
			}
			fieldValue, err := toPrettyValue(value.Field(i))
			if err != nil {
				return nil, err
			}
			result[fieldName] = fieldValue
		}
		return result, nil
	case reflect.Map:
		if value.IsNil() {
			return nil, nil
		}
		keys := value.MapKeys()
		sort.Slice(keys, func(i, j int) bool {
			return prettySortKey(keys[i]) < prettySortKey(keys[j])
		})
		entries := make([]any, 0, len(keys))
		for _, key := range keys {
			prettyKey, err := toPrettyValue(key)
			if err != nil {
				return nil, err
			}
			prettyValue, err := toPrettyValue(value.MapIndex(key))
			if err != nil {
				return nil, err
			}
			entries = append(entries, map[string]any{"key": prettyKey, "value": prettyValue})
		}
		return entries, nil
	case reflect.Slice:
		if value.IsNil() {
			return nil, nil
		}
		if value.Type().Elem().Kind() == reflect.Uint8 {
			return base64.StdEncoding.EncodeToString(value.Bytes()), nil
		}
		items := make([]any, 0, value.Len())
		for i := 0; i < value.Len(); i++ {
			item, err := toPrettyValue(value.Index(i))
			if err != nil {
				return nil, err
			}
			items = append(items, item)
		}
		return items, nil
	case reflect.Array:
		items := make([]any, 0, value.Len())
		for i := 0; i < value.Len(); i++ {
			item, err := toPrettyValue(value.Index(i))
			if err != nil {
				return nil, err
			}
			items = append(items, item)
		}
		return items, nil
	default:
		return value.Interface(), nil
	}
}

func prettyFieldName(field reflect.StructField) string {
	name := field.Tag.Get("json")
	if comma := strings.IndexByte(name, ','); comma >= 0 {
		name = name[:comma]
	}
	if name == "" {
		return field.Name
	}
	return name
}

func prettySortKey(value reflect.Value) string {
	if value.Kind() == reflect.Interface && !value.IsNil() {
		value = value.Elem()
	}
	return fmt.Sprintf("%s:%v", value.Type(), value.Interface())
}
