package binary

import (
	"encoding/base64"
	"encoding/json"
	"fmt"
	"reflect"
	"sort"
	"strconv"
	"strings"
)

// MarshalPrettyString serializes generated ByteMsg structs as indented JSON.
func MarshalPrettyString(value any) (string, error) {
	pretty, err := toPrettyValue(reflect.ValueOf(value))
	if err != nil {
		return "", err
	}
	data, err := json.MarshalIndent(pretty, "", "  ")
	if err != nil {
		return "", err
	}
	return string(data), nil
}

// UnmarshalPrettyString deserializes an indented JSON string produced by MarshalPrettyString.
func UnmarshalPrettyString(data string, target any) error {
	if target == nil {
		return fmt.Errorf("bytemsg233: nil pretty string target")
	}
	targetValue := reflect.ValueOf(target)
	if targetValue.Kind() != reflect.Pointer || targetValue.IsNil() {
		return fmt.Errorf("bytemsg233: pretty string target must be a non-nil pointer")
	}

	decoder := json.NewDecoder(strings.NewReader(data))
	decoder.UseNumber()
	var raw any
	if err := decoder.Decode(&raw); err != nil {
		return err
	}
	return fromPrettyValue(raw, targetValue.Elem())
}

func toPrettyValue(value reflect.Value) (any, error) {
	if !value.IsValid() {
		return nil, nil
	}
	if value.Kind() == reflect.Interface {
		if value.IsNil() {
			return nil, nil
		}
		return toPrettyValue(value.Elem())
	}
	if value.Kind() == reflect.Pointer {
		if value.IsNil() {
			return nil, nil
		}
		return toPrettyValue(value.Elem())
	}

	switch value.Kind() {
	case reflect.Struct:
		result := make(map[string]any, value.NumField())
		valueType := value.Type()
		for i := 0; i < value.NumField(); i++ {
			fieldInfo := valueType.Field(i)
			if fieldInfo.PkgPath != "" {
				continue
			}
			fieldName := prettyFieldName(fieldInfo)
			if fieldName == "-" {
				continue
			}
			fieldValue, err := toPrettyValue(value.Field(i))
			if err != nil {
				return nil, err
			}
			result[fieldName] = fieldValue
		}
		return result, nil
	case reflect.Map:
		if value.IsNil() {
			return nil, nil
		}
		keys := value.MapKeys()
		sort.Slice(keys, func(i, j int) bool {
			return prettySortKey(keys[i]) < prettySortKey(keys[j])
		})
		entries := make([]any, 0, len(keys))
		for _, key := range keys {
			prettyKey, err := toPrettyValue(key)
			if err != nil {
				return nil, err
			}
			prettyValue, err := toPrettyValue(value.MapIndex(key))
			if err != nil {
				return nil, err
			}
			entries = append(entries, map[string]any{"key": prettyKey, "value": prettyValue})
		}
		return entries, nil
	case reflect.Slice:
		if value.IsNil() {
			return nil, nil
		}
		if value.Type().Elem().Kind() == reflect.Uint8 {
			return base64.StdEncoding.EncodeToString(value.Bytes()), nil
		}
		items := make([]any, 0, value.Len())
		for i := 0; i < value.Len(); i++ {
			item, err := toPrettyValue(value.Index(i))
			if err != nil {
				return nil, err
			}
			items = append(items, item)
		}
		return items, nil
	case reflect.Array:
		items := make([]any, 0, value.Len())
		for i := 0; i < value.Len(); i++ {
			item, err := toPrettyValue(value.Index(i))
			if err != nil {
				return nil, err
			}
			items = append(items, item)
		}
		return items, nil
	default:
		return value.Interface(), nil
	}
}

func fromPrettyValue(raw any, target reflect.Value) error {
	if !target.CanSet() {
		return nil
	}
	if raw == nil {
		target.Set(reflect.Zero(target.Type()))
		return nil
	}

	if target.Kind() == reflect.Pointer {
		if target.IsNil() {
			target.Set(reflect.New(target.Type().Elem()))
		}
		return fromPrettyValue(raw, target.Elem())
	}

	switch target.Kind() {
	case reflect.Struct:
		object, ok := raw.(map[string]any)
		if !ok {
			return fmt.Errorf("bytemsg233: expected object for %s", target.Type())
		}
		targetType := target.Type()
		for i := 0; i < target.NumField(); i++ {
			fieldInfo := targetType.Field(i)
			if fieldInfo.PkgPath != "" {
				continue
			}
			fieldName := prettyFieldName(fieldInfo)
			if fieldName == "-" {
				continue
			}
			if fieldRaw, ok := object[fieldName]; ok {
				if err := fromPrettyValue(fieldRaw, target.Field(i)); err != nil {
					return fmt.Errorf("%s.%s: %w", targetType.Name(), fieldInfo.Name, err)
				}
			}
		}
		return nil
	case reflect.Map:
		items, ok := raw.([]any)
		if !ok {
			return fmt.Errorf("bytemsg233: expected map entries array for %s", target.Type())
		}
		result := reflect.MakeMapWithSize(target.Type(), len(items))
		for _, item := range items {
			entry, ok := item.(map[string]any)
			if !ok {
				return fmt.Errorf("bytemsg233: expected map entry object for %s", target.Type())
			}
			key := reflect.New(target.Type().Key()).Elem()
			value := reflect.New(target.Type().Elem()).Elem()
			if err := fromPrettyValue(entry["key"], key); err != nil {
				return err
			}
			if err := fromPrettyValue(entry["value"], value); err != nil {
				return err
			}
			result.SetMapIndex(key, value)
		}
		target.Set(result)
		return nil
	case reflect.Slice:
		if target.Type().Elem().Kind() == reflect.Uint8 {
			text, ok := raw.(string)
			if !ok {
				return fmt.Errorf("bytemsg233: expected base64 string for %s", target.Type())
			}
			data, err := base64.StdEncoding.DecodeString(text)
			if err != nil {
				return err
			}
			target.SetBytes(data)
			return nil
		}
		items, ok := raw.([]any)
		if !ok {
			return fmt.Errorf("bytemsg233: expected array for %s", target.Type())
		}
		result := reflect.MakeSlice(target.Type(), len(items), len(items))
		for i, item := range items {
			if err := fromPrettyValue(item, result.Index(i)); err != nil {
				return err
			}
		}
		target.Set(result)
		return nil
	case reflect.Bool:
		value, ok := raw.(bool)
		if !ok {
			return fmt.Errorf("bytemsg233: expected bool for %s", target.Type())
		}
		target.SetBool(value)
		return nil
	case reflect.String:
		value, ok := raw.(string)
		if !ok {
			return fmt.Errorf("bytemsg233: expected string for %s", target.Type())
		}
		target.SetString(value)
		return nil
	case reflect.Int, reflect.Int8, reflect.Int16, reflect.Int32, reflect.Int64:
		value, err := prettyInt(raw)
		if err != nil {
			return err
		}
		if target.OverflowInt(value) {
			return fmt.Errorf("bytemsg233: integer %d overflows %s", value, target.Type())
		}
		target.SetInt(value)
		return nil
	case reflect.Uint, reflect.Uint8, reflect.Uint16, reflect.Uint32, reflect.Uint64, reflect.Uintptr:
		value, err := prettyUint(raw)
		if err != nil {
			return err
		}
		if target.OverflowUint(value) {
			return fmt.Errorf("bytemsg233: unsigned integer %d overflows %s", value, target.Type())
		}
		target.SetUint(value)
		return nil
	case reflect.Float32, reflect.Float64:
		value, err := prettyFloat(raw)
		if err != nil {
			return err
		}
		if target.OverflowFloat(value) {
			return fmt.Errorf("bytemsg233: float %g overflows %s", value, target.Type())
		}
		target.SetFloat(value)
		return nil
	case reflect.Interface:
		target.Set(reflect.ValueOf(raw))
		return nil
	default:
		return fmt.Errorf("bytemsg233: unsupported pretty string target %s", target.Type())
	}
}

func prettyFieldName(field reflect.StructField) string {
	name := field.Tag.Get("json")
	if comma := strings.IndexByte(name, ','); comma >= 0 {
		name = name[:comma]
	}
	if name == "" {
		return field.Name
	}
	return name
}

func prettySortKey(value reflect.Value) string {
	if value.Kind() == reflect.Interface && !value.IsNil() {
		value = value.Elem()
	}
	return fmt.Sprintf("%s:%v", value.Type(), value.Interface())
}

func prettyInt(raw any) (int64, error) {
	switch value := raw.(type) {
	case json.Number:
		return value.Int64()
	case float64:
		return int64(value), nil
	default:
		return 0, fmt.Errorf("bytemsg233: expected integer, got %T", raw)
	}
}

func prettyUint(raw any) (uint64, error) {
	switch value := raw.(type) {
	case json.Number:
		return strconv.ParseUint(value.String(), 10, 64)
	case float64:
		return uint64(value), nil
	default:
		return 0, fmt.Errorf("bytemsg233: expected unsigned integer, got %T", raw)
	}
}

func prettyFloat(raw any) (float64, error) {
	switch value := raw.(type) {
	case json.Number:
		return value.Float64()
	case float64:
		return value, nil
	default:
		return 0, fmt.Errorf("bytemsg233: expected float, got %T", raw)
	}
}
